DISTRO = "bradfa-container-distro"
DISTRO_NAME = "bradfa-container-distro"
DISTRO_VERSION = "1.0+snapshot-${METADATA_REVISION}"
DISTRO_CODENAME = "wrynose"

DISTRO_FEATURES = " \
    acl \
    ipv4 \
    ipv6 \
    minidebuginfo \
    seccomp \
    usrmerge \
    virtualization \
    xattr \
"

# We don't need an init in containers so setup the most minimal one possible
INIT_MANAGER = "mdev-busybox"
VIRTUAL-RUNTIME_init_manager = ""
VIRTUAL-RUNTIME_dev_manager = ""
VIRTUAL-RUNTIME_login_manager = ""
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_sysklogd = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
