# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-bradfa-ai-distro"
BBFILE_PATTERN_meta-bradfa-ai-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bradfa-ai-distro = "6"

LAYERDEPENDS_meta-bradfa-ai-distro = "core"
LAYERSERIES_COMPAT_meta-bradfa-ai-distro = "wrynose"
